function [parameterStr] = asmGetParameterStr(asmCase)
    
    parameterStr = ['A=',num2str(asmCase.A,'%.2f'), ...
        ' Ra=',num2str(asmCase.realRa,'%1.2E'), ...
        ' Ra_b=',num2str(asmCase.Ra,'%1.2E'), ...
        ' r_c=',num2str(asmCase.r_c,'%g'), ...
        ' W=',num2str(asmCase.W,'%.2f')];

end