function [parameterStr] = asmGetParameterStr(asmCase)

    if isfield(asmCase,'modelName') && isfield(asmCase,'typobs')
        modelStr = ['Model=',asmCase.modelName, ...
            ' TYPOBS=',num2str(asmCase.typobs,'%d')];
    else
        modelStr = 'Model=Legacy';
    end

    if isfield(asmCase,'isFTB') && asmCase.isFTB
        parameterStr = [modelStr, ...
            ' A=',num2str(asmCase.A,'%.2f'), ...
            ' Ra=',num2str(asmCase.realRa,'%1.2E'), ...
            ' Ra_b=',num2str(asmCase.Ra,'%1.2E'), ...
            ' r_c=',num2str(asmCase.r_c,'%g'), ...
            ' W=',num2str(asmCase.W,'%.2f')];
    elseif isfield(asmCase,'hasNonlinearRayleighFriction') && ...
            asmCase.hasNonlinearRayleighFriction
        parameterStr = [modelStr, ...
            ' Ra=',num2str(asmCase.Ra,'%1.2E'), ...
            ' u0=',num2str(asmCase.rayleighVelocityThreshold,'%g'), ...
            ' alpha=',num2str(asmCase.rayleighActivationRate,'%g')];
    else
        parameterStr = [modelStr, ...
            ' Ra=',num2str(asmCase.Ra,'%1.2E')];
    end

end
