% this function shows the case start time, end time and number of steps
function asmShowCase(asmCase)
    numCase = asmCase.numSubCase;
    disp('Physical Parameter:')
    disp(['A=',num2str(asmCase.A,'%.2f'), ...
        ' W=',num2str(asmCase.W,'%.2f'), ...
        ' Ra=',num2str(asmCase.realRa,'%1.2E'), ...
        ' Ra_b=',num2str(asmCase.Ra,'%1.2E'), ...
        ' r_c=',num2str(asmCase.r_c,'%g')])
    disp(['This assemble case simulated the totoal time: ', num2str(asmCase.dnsStopTime,'%g')]);
    disp('It have the following sub cases:');
    for i = 1:numCase
        disp(['sub case No. ',num2str(i,'%d'), ' in: ',asmCase.subCaseDir{i}])
        if i == 1
            numSteps = asmCase.endTime(i)/asmCase.dtSave(i);
        else
            numSteps = (asmCase.endTime(i) - asmCase.endTime(i-1))/asmCase.dtSave(i);
        end
        disp(['Start from ',num2str(asmCase.startTime(i),'%g'), ...
            ' End at ',num2str(asmCase.endTime(i),'%g'),...
            ' Resolution ',num2str(asmCase.n1(i),'%d'), ...
            ' Number Steps ',num2str(numSteps,'%d'), ...
            ' dt Save ',num2str(asmCase.dtSave(i),'%g')])
    end
end