function [asmCase] = setAsmCaseEmpty()
    
    asmCase = struct([]);
    
    asmCase(1).A = [];
    asmCase(1).dataFileName = [];
    asmCase(1).Delta = [];
    asmCase(1).dnsBeginTime = [];
    asmCase(1).dnsStopTime = [];
    asmCase(1).dt = [];
    asmCase(1).dtSave = [];
    asmCase(1).endTime = [];
    asmCase(1).Ff = [];
    asmCase(1).H = [];
    asmCase(1).h1 = [];
    asmCase(1).h2 = [];
    asmCase(1).IDGOM = [];
    asmCase(1).IDSOLU = [];
    asmCase(1).invRo = [];
    asmCase(1).lastReadTime = [];
    asmCase(1).maxN = [];
    asmCase(1).n1 = [];
    asmCase(1).n2 = [];
    asmCase(1).nextReadTime = [];
    asmCase(1).numSubCase = [];
    asmCase(1).Pr = [];
    asmCase(1).r_c = [];
    asmCase(1).Ra = [];
    asmCase(1).readCounter = [];
    asmCase(1).readNowFileID = [];
    asmCase(1).readNowSubCaseIdx = [];
    asmCase(1).realRa = [];
    asmCase(1).St = [];
    asmCase(1).startTime = [];
    asmCase(1).subCaseDir = [];
    asmCase(1).theta_c = [];
    asmCase(1).theta_c_deg = [];
    asmCase(1).time = [];
    asmCase(1).timeLocal = [];
    asmCase(1).timePrecision = [];
    asmCase(1).totalN = [];
    asmCase(1).type = [];
    asmCase(1).W = [];
    asmCase(1).x2dDroit = [];
    asmCase(1).x2dGauche = [];
    asmCase(1).x2dS = [];
    asmCase(1).x2dU = [];
    asmCase(1).x2dV = [];
    asmCase(1).y2dBas = [];
    asmCase(1).y2dHaut = [];
    asmCase(1).y2dS = [];
    asmCase(1).y2dU = [];
    asmCase(1).y2dV = [];

end