function [epsilonU] = dnsGetEpsilonU(dns,subCaseIdx,u2dOrgMsh,v2dOrgMsh,itpMesh)

    [gradU] = dnsGradVel3D(dns,subCaseIdx,u2dOrgMsh,v2dOrgMsh,itpMesh);

    s_11 = 0.5*(gradU.dudx + gradU.dudx);
    s_12 = 0.5*(gradU.dudy + gradU.dvdx);
    s_13 = 0.5*(gradU.dudz + gradU.dwdx);
    s_21 = 0.5*(gradU.dvdx + gradU.dudy);
    s_22 = 0.5*(gradU.dvdy + gradU.dvdy);
    s_23 = 0.5*(gradU.dvdz + gradU.dwdy);
    s_31 = 0.5*(gradU.dwdx + gradU.dudz);
    s_32 = 0.5*(gradU.dwdy + gradU.dvdz);
    s_33 = 0.5*(gradU.dwdz + gradU.dwdz);

    nu_nondimensiion = sqrt(dns.Pr/dns.Ra);

    epsilonU = 2*nu_nondimensiion*( ...
                s_11.*s_11 + ...
                s_12.*s_12 + ...
                s_13.*s_13 + ...
                ...
                s_21.*s_21 + ...
                s_22.*s_22 + ...
                s_23.*s_23 + ...
                ...
                s_31.*s_31 + ...
                s_32.*s_32 + ...
                s_33.*s_33 ...
            );
end