function [configList] = getCaseDirListRc09(rootPath)
    % configList(1).caseDir{1} = ...
    % 'Ra3e3_r_c_0.9/00_1_iniTmp0_256/';
    % 
    % configList(n).caseDir{1} = ...
    % 'Ra3e4_r_c_0.9/00_1_iniTmp0_256/';
    
    % configList(1).caseDir{1} = ...
    % 'Ra3e5_r_c_0.9/00_1_iniTmp0_256/';
    
    n = 1;
    folderName = '4_Ra3e6';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'00_1_256/');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'00_2_1024/');
    
    n = n + 1;
    folderName = '5_Ra3e7';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'00_1_256/');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'00_2_1024/');
    configList(n).caseDir{3} = ...
        fullfile(folderName,'00_3_1024/');
    
    n = n + 1;
    folderName = '6_Ra3e8';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'00_1_256/');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'00_2_1024/');
    configList(n).caseDir{3} = ...
        fullfile(folderName,'00_3_1536/');
    configList(n).caseDir{4} = ...
        fullfile(folderName,'00_4_1536/');
    
    n = n + 1;
    folderName = '7_Ra3e9';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'49_1_1536/');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'49_2_1536/');
    configList(n).caseDir{3} = ...
        fullfile(folderName,'49_3_2048/');
    
    n = n + 1;
    folderName = '8_Ra3e10';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'1_1_2048/');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'1_2_2048/');
    configList(n).caseDir{3} = ...
        fullfile(folderName,'1_3_2048/');
    configList(n).caseDir{4} = ...
        fullfile(folderName,'1_4_2048/');
    configList(n).caseDir{5} = ...
        fullfile(folderName,'1_5_2048/');
    configList(n).caseDir{6} = ...
        fullfile(folderName,'1_6_3072/');
    
    n = n + 1;
    folderName = '9_Ra3e11';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'1_1_2048/');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'1_2_2048/');
    configList(n).caseDir{3} = ...
        fullfile(folderName,'1_3_2048/');
    configList(n).caseDir{4} = ...
        fullfile(folderName,'1_4_2048/');
    configList(n).caseDir{5} = ...
        fullfile(folderName,'1_5_2048/');
    configList(n).caseDir{6} = ...
        fullfile(folderName,'1_6_3072/');
    
    n = n + 1;
    folderName = '10_Ra3e12';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'1_1_2048/');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'1_2_2048/');
    configList(n).caseDir{3} = ...
        fullfile(folderName,'1_3_2048/');
    configList(n).caseDir{4} = ...
        fullfile(folderName,'1_4_2048/');
    configList(n).caseDir{5} = ...
        fullfile(folderName,'1_5_3072/');
    configList(n).caseDir{6} = ...
        fullfile(folderName,'1_6_4096/');
    configList(n).caseDir{7} = ...
        fullfile(folderName,'1_7_4096/');
    configList(n).caseDir{8} = ...
        fullfile(folderName,'1_8_4096/');
    configList(n).caseDir{9} = ...
        fullfile(folderName,'1_10_256/');
    configList(n).caseDir{10} = ...
        fullfile(folderName,'1_11_512/');
    configList(n).caseDir{11} = ...
        fullfile(folderName,'1_12_1024/');
    configList(n).caseDir{12} = ...
        fullfile(folderName,'1_13_1024/');
    configList(n).caseDir{13} = ...
        fullfile(folderName,'1_14_1024/');
    % configList(n).caseDir{9} = ...
    % 'Ra3e12_r_c_0.9/1_9_6144/';

%     configList(8).caseDir{1} = ...
%     'Ra3e13_r_c_0.9/1_1_initZero_2048/';
    
    for idxConfig = 1:numel(configList)
        for idxSubCase = 1:numel(configList(idxConfig).caseDir)
            configList(idxConfig).caseDir{idxSubCase} = ...
                fullfile(rootPath,configList(idxConfig).caseDir{idxSubCase});
        end
    end

end

