function [configList] = getCaseDirListRc001_2(rootPath)
    n = 1;
    % folderName = '1_Ra9e2';
    % configList(n).caseDir{1} = ...
    %     fullfile(folderName,'1_1_256/');
    % configList(n).caseDir{2} = ...
    %     fullfile(folderName,'1_2_1536/');
    % 
    % n = n + 1;
    folderName = '2_Ra3e3';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'00_1_256');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'00_2_1024');
    configList(n).caseDir{3} = ...
        fullfile(folderName,'00_3_1024');
    configList(n).caseDir{4} = ...
        fullfile(folderName,'00_4_1024');
    configList(n).caseDir{5} = ...
        fullfile(folderName,'00_5_1536');
    configList(n).caseDir{6} = ...
        fullfile(folderName,'00_6_2048');
    
    n = n + 1;
    folderName = '3_Ra9e3';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'1_1_256');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'1_2_1536');
    configList(n).caseDir{3} = ...
        fullfile(folderName,'1_3_1536');
    
    n = n + 1;
    folderName = '4_Ra3e4';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'00_1_256');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'00_2_1024');
    configList(n).caseDir{3} = ...
        fullfile(folderName,'00_3_1024');
    configList(n).caseDir{4} = ...
        fullfile(folderName,'00_4_1024');
    configList(n).caseDir{5} = ...
        fullfile(folderName,'00_5_1536');
    configList(n).caseDir{6} = ...
        fullfile(folderName,'00_6_2048');

    n = n + 1;
    folderName = '5_Ra9e4';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'1_1_256');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'1_2_256');
    configList(n).caseDir{3} = ...
        fullfile(folderName,'1_3_2048');
    
    n = n + 1;
    folderName = '6_Ra3e5';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'00_1_256');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'00_2_512');
    configList(n).caseDir{3} = ...
        fullfile(folderName,'00_3_1024');
    configList(n).caseDir{4} = ...
        fullfile(folderName,'00_4_1024');
    configList(n).caseDir{5} = ...
        fullfile(folderName,'00_5_1024');
    configList(n).caseDir{6} = ...
        fullfile(folderName,'00_6_1536');
    configList(n).caseDir{7} = ...
        fullfile(folderName,'00_7_1536');

    n = n + 1;
    folderName = '7_Ra9e5';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'1_1_256');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'1_2_256');
    configList(n).caseDir{3} = ...
        fullfile(folderName,'1_3_1536');
    
    n = n + 1;
    folderName = '8_Ra3e6';
    configList(n).caseDir{1} = ...
        fullfile(folderName,'04_1_1024');
    configList(n).caseDir{2} = ...
        fullfile(folderName,'04_2_1024');
    configList(n).caseDir{3} = ...
        fullfile(folderName,'04_3_1024');
    configList(n).caseDir{4} = ...
        fullfile(folderName,'04_4_1024');
    configList(n).caseDir{5} = ...
        fullfile(folderName,'04_5_1536');
    configList(n).caseDir{6} = ...
        fullfile(folderName,'04_6_1536');
    configList(n).caseDir{7} = ...
        fullfile(folderName,'04_7_1536');


    % configList(n).caseDir{1} = ...
    % 'Ra3e7_r_c_0.01/02_1_initTmp0_1024/';
    % 
    % configList(n).caseDir{1} = ...
    % 'Ra3e8_r_c_0.01/03_1_iniTmp0_1024/';
    % 
    % configList(n).caseDir{1} = ...
    % 'Ra3e9_r_c_0.01/44_1_iniTmp0_1536/';
   

    for idxConfig = 1:numel(configList)
        for idxSubCase = 1:numel(configList(idxConfig).caseDir)
            configList(idxConfig).caseDir{idxSubCase} = ...
                fullfile(rootPath,configList(idxConfig).caseDir{idxSubCase});
        end
    end
end

